-- Seed data for auth.db (users table)
-- Creates users matching sports users. Passwords are PBKDF2-SHA256 hashes generated by app.passwords.
-- Logins and default passwords:
--  - admin / admin123
--  - ivan / password123
--  - maria / password123
--  - daniil / password123
--  - tina / password123

PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

-- Create table if missing (idempotent)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_login_at TEXT
);

-- Clear existing users
DELETE FROM users;

-- Insert users with precomputed hashes and timestamps
INSERT INTO users (id, login, password_hash, created_at, last_login_at) VALUES
  (1, 'admin',  'pbkdf2_sha256$240000$mnjhjn1Td0HmUNEFrg_52g$85Cp9c2DyB8Q27bXeWdJtAv42ouJilgKwBqSGjkEIQ',  strftime('%Y-%m-%dT%H:%M:%SZ','now'), NULL),
  (2, 'ivan',   'pbkdf2_sha256$240000$ycyiB8I2xIY3jLkfC9PSgA$Xf7KoHJuPxg4AFPFcbAfIw9HQyMoV8s5rkv9SfF9X5Y',  strftime('%Y-%m-%dT%H:%M:%SZ','now'), NULL),
  (3, 'maria',  'pbkdf2_sha256$240000$3sh7r9tWAS_sQhptyFFOGA$vUlAjrjlzlxXZNQpVf39VtirlNKYzW39lsAH85mtK9A',  strftime('%Y-%m-%dT%H:%M:%SZ','now'), NULL),
  (4, 'daniil', 'pbkdf2_sha256$240000$RQpAuFdUtP4QGRCZBxFOUA$KfV2hPpV6NS1E50yxW3ybBGxJCX2DD6IHNh-ePpawe8', strftime('%Y-%m-%dT%H:%M:%SZ','now'), NULL),
  (5, 'tina',   'pbkdf2_sha256$240000$oyHNoyEaWTUV17bbkUEIrA$N93QoS6rtmR8SvA_Bz3SE6I9dbCVS_Wae5f_hlx4gcY',  strftime('%Y-%m-%dT%H:%M:%SZ','now'), NULL);

COMMIT;
